### ISSUE TITLE
cant find training script for MOODv2

### ISSUE THREAD

**Issue by harshnandwana** [dvlab-research/MOOD#8]
Hey Team 
i cant find the method to train or finetune the model also i wish to use this model as an api where if i pass a image the model can tell if it is an ood or not for that is there a script for prediction where i can get the knowledge of it is an outlier or not

**Comment by JulietLJY** [comment]
Hi, we have uploaded the links to the  [training scripts](https://github.com/dvlab-research/MOOD/tree/master/MOODv2#pretrained-model-preparation) of our evaluated models and the [demo](https://github.com/dvlab-research/MOOD/tree/master/MOODv2#demo) to predict if an image is an outlier or not.  Hope you enjoy using them.
