### ISSUE TITLE
problems while running src/extract_feature_vit.py

### ISSUE THREAD

**Issue by harshnandwana** [dvlab-research/MOOD#9]
if im using any command 
1.  python3 src/extract_feature_vit.py $IMAGENET_PATH    --cfg configs/beit-base-p16_224px.py    --checkpoint pretrain/epoch_19.pth --fc_save_path output/fc.pkl
2.  python src/extract_feature_vit.py $IMAGENET_PATH    --out_file outputs/imagenet_train.pkl    --cfg configs/beit-base-p16_224px.py    --checkpoint pretrain/beitv2-base.pth    --img_list datalists/imagenet2012_train_random_200k.txt

im getting below given error

Traceback (most recent call last):
  File "src/extract_feature_vit.py", line 12, in <module>
    from .list_dataset import ImageFilelist
ImportError: attempted relative import with no known parent package

**Comment by JulietLJY** [comment]
The issue has been resolved by replacing `from .list_dataset import ImageFilelist` with `from list_dataset import ImageFilelist`. You can either modify line 12 of `src/extract_feature_vit.py` or update the repository.

**Comment by harshnandwana** [comment]
thanks it worked
